import { FC } from 'react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import DetailsComponent from '../../screens/details';

const Details: FC<{id: string}> = (props) => {
  const { id } = props;

  return (
    <>
      <Head>
        <title>Detalhes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DetailsComponent id={Number(id)} />
    </>
  );
};

export default Details;

export const getServerSideProps = (ctx: GetServerSidePropsContext) => ({ props: ctx.query });
