import { FC } from 'react';
import Head from 'next/head';

import DetailsContent from '../screens/cart';

const Details: FC = () => (
  <>
    <Head>
      <title>Carrinho de compras</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <DetailsContent />
  </>
);

export default Details;
