import { FC } from 'react';
import Head from 'next/head';
import DetailsContent from '../screens/details';

const Details: FC = () => (
  <>
    <Head>
      <title>Details</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <DetailsContent />
  </>
);
export default Details;
