import type { NextPage } from 'next';
import { useCallback } from 'react';
import { ThemeProvider, DefaultTheme } from 'styled-components';
import Head from 'next/head';
import { LIGHT } from '../styles/themes/light';
import { DARK } from '../styles/themes/dark';
import { usePersistedState } from '../utils/usePersistedState';
import { Container } from '../styles/home.styles';
import HomePage from '../screens/home';

const Home: NextPage = () => {
  const [theme, setTheme] = usePersistedState<DefaultTheme>('theme', LIGHT);

  const handleTheme = useCallback(() => {
    setTheme(theme.type === 'light' ? DARK : LIGHT);
  }, [theme]);

  return (
    <ThemeProvider theme={theme}>
      <Container>
        <Head>
          <title>Buy-me</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HomePage handleTheme={handleTheme} />

      </Container>
    </ThemeProvider>
  );
};

export default Home;
