import type { NextPage } from 'next';
import Head from 'next/head';
import { Container } from '../styles/home.styles';
import HomePage from '../screens/home';

const Home: NextPage = () => (
  <Container>
    <Head>
      <title>Buy-me</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <HomePage />

  </Container>

);

export default Home;
